/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./js/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#2d4b3e",
        "on-primary-fixed": "#0b1e15",
        "secondary-fixed": "#c8ead8",
        "outline": "#c1c8c3",
        "inverse-primary": "#8ad0ae",
        "tertiary-container": "#2c3647",
        "surface-container-high": "#e7e9e4",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#0b1e15",
        "secondary-fixed-dim": "#a5deb8",
        "tertiary-fixed": "#d9e3f9",
        "on-secondary-container": "#163428",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f2f4f0",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#3d4759",
        "outline-variant": "#c1c8c3",
        "tertiary-fixed-dim": "#bdc7dc",
        "on-tertiary-container": "#959fb3",
        "primary-fixed": "#c8ead8",
        "on-tertiary": "#ffffff",
        "surface": "#f8faf5",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e1e3df",
        "background": "#f8faf5",
        "on-background": "#163428",
        "secondary": "#424844",
        "surface-container": "#f2f4f0",
        "error": "#ba1a1a",
        "surface-dim": "#d9dbd7",
        "on-error-container": "#93000a",
        "on-surface-variant": "#424844",
        "on-tertiary-fixed": "#121c2c",
        "primary-fixed-dim": "#a5deb8",
        "on-primary-container": "#0b1e15",
        "primary": "#2d4b3e",
        "on-surface": "#163428",
        "surface-variant": "#e1e3df",
        "surface-container-low": "#f5f7f2",
        "primary-container": "#c8ead8",
        "on-primary-fixed-variant": "#163428",
        "surface-bright": "#f8faf5",
        "secondary-container": "#a5deb8",
        "tertiary": "#172131",
        "inverse-surface": "#163428",
        "surface-tint": "#2d4b3e"
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [require('@tailwindcss/forms')],
}